### PR TITLE
Fix nanoQC Breakage from pip install, added GC Percentage Calculation

### PR DESCRIPTION
**Pull request by PuneetSivananda**
### GC Percentage Calculation

- Calculate GC% using seqIO package and plot the graph from the sorted reads sampled
- Calculate GC% and plot the graph from the reads sampled

### CODE REVIEW

**Comment by wdecoster** [comment]
I see you marked this as a draft, so you probably still have plans here. Let me know when I can have a look, but that will be delayed due to the holidays.

**Comment by PuneetSivananda** [comment]
No worries, i have completed the updates please review and let me know any updates based on the approach

I am marking the PR from draft to open, ready for your review.

note: not calculating the GC% manually using the biopython lib for the same

**Comment by PuneetSivananda** [comment]
@wdecoster Hi,  have you had time to review this PR, Thanks

**Comment by PuneetSivananda** [comment]
@wdecoster i am unable to assign this PR to you can you add me as a contributor

**Comment by wdecoster** [comment]
> @wdecoster i am unable to assign this PR to you can you add me as a contributor

I will not. 

Your code does not show the GC percentage per position in the read, it calculates the gc_fraction per read (not per position) and plots that against the arbitrary index within the list of seqs. Furthermore, you combine head and tail sequences without distinguishing where they came from.  The output is incorrect.

There are other things that I had to change to get the code to run, and I set up a branch for those changes: https://github.com/wdecoster/nanoQC/tree/test_gc

**Comment by PuneetSivananda** [comment]
Thanks, will rework on the GC Percentage to per position in the read, 
will distinguish the head and tail sequences

**Pull request closed without merging**
